# Use the official Go image as a base image
FROM golang:1.24-alpine AS builder

RUN apk add make

## Sonar Scanner



# Set the working directory inside the container
WORKDIR /app

# Copy the go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the working directory inside the container
COPY . .
COPY etc/config ./etc/config
