services:
  redis:
    image: redis:latest
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
    - "6379:6379"

networks:
  fizzbuzz:
    driver: bridge