services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/bin/api", "api" ]
    hostname: api
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ENV=dev
      - REDIS_ADDRESS=redis:6379
    ports:
      - "8080:9090"
    networks:
      - fizzbuzz

  redis:
    image: redis:latest
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
    - "6379:6379"
    networks:
      - fizzbuzz

  # Swagger UI for API documentation
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /oas/swagger.yml
    ports:
      - "9091:8080"
    volumes:
      - ./docs:/oas

networks:
  fizzbuzz:
    driver: bridge