services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/api --config_path ./etc/config/
    hostname: api
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ENV=dev
      - HTTP_SERVER_HOST=:8080
      - REDIS_ADDRESS=redis:6379
      - CONFIG_PATH=./etc/config/
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
    - "6379:6379"

  # Swagger UI for API documentation
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /oas/swagger.yml
    ports:
      - "8081:8080"
    volumes:
      - ./docs:/oas